apiVersion: v1
data:
  default.conf: "server {\n    listen       80;\n    listen  [::]:80;\n    server_name
    \ localhost;\n\n    #access_log  /var/log/nginx/host.access.log  main;\n\n    #location
    / {\n    #    root   /usr/share/nginx/html;\n    #    index  index.html index.htm;\n
    \   #}\n\n    #error_page  404              /404.html;\n\n    # redirect server
    error pages to the static page /50x.html\n    #\n    error_page   500 502 503
    504  /50x.html;\n    location = /50x.html {\n        root   /usr/share/nginx/html;\n
    \   }\n\n    # proxy the PHP scripts to Apache listening on 127.0.0.1:80\n    #\n\n\n
    \   location / {\n         auth_basic              \"Restricted\";\n         auth_basic_user_file
    \   auth.htpasswd;\n        \n        \n        proxy_pass   http://hello-world:5000;\n
    \   }\n\n    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000\n
    \   #\n    #location ~ \\.php$ {\n    #    root           html;\n    #    fastcgi_pass
    \  127.0.0.1:9000;\n    #    fastcgi_index  index.php;\n    #    fastcgi_param
    \ SCRIPT_FILENAME  /scripts$fastcgi_script_name;\n    #    include        fastcgi_params;\n
    \   #}\n\n    # deny access to .htaccess files, if Apache's document root\n    #
    concurs with nginx's one\n    #\n    #location ~ /\\.ht {\n    #    deny  all;\n
    \   #}\n}"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-09T13:07:00Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:default.conf: {}
    manager: rancher
    operation: Update
    time: "2022-01-09T13:07:00Z"
  name: default.conf
  namespace: default
  resourceVersion: "79362"
  uid: 0e90ed11-35d5-41a7-b079-3ce323ca9ce9
